---
title: "Project work part 5: Modelling"
subtitle: "Group 1"
author: 
 - Danli Shen
 - Dave Rojas
 - Mathias N. Stokholm
 - Ziyu Zhang
 - Karolina Krzesińska
date: '2022-04-06'
output: pdf_document
---

Phosphate as function of temperature
Nitrate as f of temperature

## Load packages
```{r echo = T, results = 'hide', message = FALSE, warning = FALSE}
library(tidyverse)
library(readxl)
```

## Load data
```{r}
envDat <- readxl::read_excel("../data/Env_data_mec-14-1145.xlsx") %>% 
  mutate(across(where(is.character), ~na_if(., "NA"))) %>% 
  rename(Date = "Date (dd.mm.yy)")
```



```{r}
mdls <- envDat %>%
  select(contains("mean")) %>% 
  mutate(across(.fns = as.numeric)) %>% 
  pivot_longer(cols = -Temp.mean,
               names_to = "Parameter",
               values_to = "Value") %>% 
  group_by(Parameter) %>% 
  nest() %>% 
  ungroup() %>% 
  mutate(mdl = map(data, ~lm(Value ~ Temp.mean, data = .x))) %>% 
  mutate(mdl_details = map(mdl, broom::tidy, conf.int = TRUE)) %>% 
  unnest(mdl_details)

mdls  %>% 
  filter(term != "(Intercept)") %>% 
  select(Parameter, estimate, p.value) %>% 
  arrange(p.value)
```

Phos.mean is the only significant one with a p-value less than 0.05, therefore we continue with this one.

```{r}
mdl.param <- mdls %>% 
  filter(Parameter == "Phos.mean") %>% 
  select(term, estimate, conf.low, conf.high) 
mdl.param
```

We prepare the data by removing NAs:
```{r}
mdl.data <- envDat %>% 
  select(Temp.mean,
         Phos.mean) %>% 
  drop_na() %>% 
  mutate(Phos.mean = Phos.mean %>% as.numeric,
         Temp.mean = Temp.mean %>% as.numeric)
  
```


```{r}
datapoints <- geom_point(mapping = aes(y = Phos.mean),
                         color = "red",
                         shape = 18,
                         size = 3)
regression_line <- geom_line(data = mdl.data,
                             mapping = aes(y = 0.403 + -0.020 * Temp.mean))
lower_bound <- geom_line(data = mdl.data,
                             mapping = aes(y = 0.262 + -0.034 * Temp.mean),
                         linetype = "dashed")
upper_bound <- geom_line(data = mdl.data,
                             mapping = aes(y = 0.544 + -0.005 * Temp.mean),
                         linetype = "dashed")

ggplot(data = mdl.data,
       mapping = aes(x = Temp.mean)) +
  datapoints +
  regression_line +
  lower_bound +
  upper_bound +
  labs(x = "Temperature (°C)",
       y = "Phosphate (μM)",
       title = "Phosphate concentration as a function of temperature",
       subtitle = "Averaged over the mixed layer") +
  theme_classic()
```


